#!/usr/bin/env python3
# encoding: utf-8

from .configmanager import CONFIG_MANAGER

CONKYRC_TOP = """
-- This file gets automatically generated by build_conkyrc.py
conky.config = {
"""
CONKYRC_BOTTOM = """
    total_run_times = 0,
    alignment = 'top_right',
    background = true,
    own_window = true,
    own_window_type = 'desktop',
    own_window_transparent = true, --false, -- Set to true for full transparancy
    own_window_hints = 'undecorated,sticky,skip_taskbar,skip_pager,below',

    out_to_console = false,
    out_to_stderr = false,
    override_utf8_locale = true,
    double_buffer = true,
    draw_shades = false,
    draw_outline = false,
    draw_borders = false,
    stippled_borders = 0,
    default_color = white,
    no_buffers = true,
    uppercase = false,
    use_spacer = left,
    -- important, standard size for var buffer is 128bit
    imlib_cache_size = 0,
    text_buffer_size = 6000

    }

"""

def build_conkyrc(path):
    rc = CONKYRC_TOP +\
        "    update_interval = %i,\n" % CONFIG_MANAGER.getInt("General", "ConkyUpdate") +\
        "    gap_x = %i,\n" % CONFIG_MANAGER.getInt("General", "ConkyGapX") +\
        "    gap_y = %i,\n" % CONFIG_MANAGER.getInt("General", "ConkyGapY") +\
        "    minimum_height = %i,\n" % CONFIG_MANAGER.getInt("General", "ConkyHeight") +\
        "    minimum_width = %i,\n" % CONFIG_MANAGER.getInt("General", "ConkyWidth") +\
        CONKYRC_BOTTOM +\
        "conky.text = [[ ${execpi %i python3.9 -m conkyKeep -n } ]]" % CONFIG_MANAGER.getInt("General", "ConkyKeepUpdate") +\
        "\n"
    with open(path, 'w') as f:
        f.write(rc)
